import Landing from "./Landing";
import Register from "./Register";
import Post from "./Post";
import User_Profile from "./User_Profile";
import Home from "./Home";
import Chat from "./test";
import Chatroom from "./Chatroom";
import Verify_OTP from "./Verify_OTP";
import ForgotPassword from "./ForgotPassword";
import Verify_OTP_forgot from "./VerifyOTP.forgot";
export { Landing ,Register,Home, Post,User_Profile,Chat,Chatroom,Verify_OTP,ForgotPassword,Verify_OTP_forgot };